name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "* * * * *"

jobs:
  stale:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        daysUntilStale: 45
        daysUntilClose: 14
        exemptLabels: 'help wanted', security
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-issue-label: 'itstaleyall'
